### ISSUE TITLE
House

### ISSUE THREAD

**Issue by effoc** [Ninja-FSE/pmm-config#11]
metadata:    
    "House (2004)":
        year: 2004
        title: "House"
        url_poster: https://theposterdb.com/api/assets/278643
        match:
          mapping_id: 1408
        # IDs: imdb://tt9319668, tmdb://90669, tvdb://384429
        # tpdb: https://theposterdb.com/search/advanced/results?term=1899&category=Shows&year_filter=equals&yone=2022&tmdb_id=90669&imdb_id=tt9319668&tvdb_id=384429
        # tmdb: https://www.themoviedb.org/tv/90669
        # tvdb: https://thetvdb.com/search?menu%5Btype%5D=series&menu%5Byear%5D=2022&query=384429
        # imdb: https://www.imdb.com/title/tt9319668
        seasons:
            1:
                url_poster: https://theposterdb.com/api/assets/278645
            2:
                url_poster: https://theposterdb.com/api/assets/278646  
            3:
                url_poster: https://theposterdb.com/api/assets/278647
            4:
                url_poster: https://theposterdb.com/api/assets/278648
            5:
                url_poster: https://theposterdb.com/api/assets/278649
            6:
                url_poster: https://theposterdb.com/api/assets/278650       
            7:
                url_poster: https://theposterdb.com/api/assets/278651
            8:
                url_poster: https://theposterdb.com/api/assets/278652

**Comment by Ninja-FSE** [comment]
Please use code brackets ``` text here ```
